name: jaguar_hotreload
description: Hot reloader for Dart. Reloads your application whenever a file system change is detected in the source files or registered files.
version: 2.0.2
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
- Günter Zöchbauer <guenter@gzoechbauer.com>
homepage: https://github.com/Jaguar-dart/jaguar_hotreload
documentation:

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  vm_service_lib: ^0.3.5
  watcher: ^0.9.7
  glob: ^1.1.3

dev_dependencies:
  test: ^1.0.0
  pedantic: ^1.1.0
