name: jaguar_hotreload
description: Hot reloader for Dart
version: 0.2.3
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_hotreload
documentation:

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  vm_service_lib: ^0.3.5
  watcher: ^0.9.7
  glob: ^1.1.3

dev_dependencies:
  test: ^0.12.0
